FROM oven/bun

WORKDIR /app



COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./packages/database/package.json ./packages/database/package.json
COPY ./apps/ws-backend/package.json ./apps/ws-backend/package.json


COPY ./packages ./packages
COPY ./apps/ws-backend ./apps/ws-backend

RUN bun install

EXPOSE 3002

RUN cd packages/database && bunx prisma generate

CMD ["bun", "run", "--cwd", "apps/ws-backend", "index.ts"]